name: Build and Release Electron App

on:
    push:
        tags:
            - 'v*.*.*'
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, windows-latest]

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - uses: pnpm/action-setup@v3
              with:
                  version: '9'

            - name: Cache pnpm store
              uses: actions/cache@v4
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build Electron App
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: pnpm run dist

            - name: Upload Installers
              uses: actions/upload-artifact@v4
              with:
                  name: electron-installers-${{ matrix.os }}
                  path: dist/

    release:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts/

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: artifacts/**/*.*
